#!/bin/lua

-- required to load scripts
local river_path = os.getenv("HOME") .. "/.config/river/?.lua"
package.path = package.path .. ";" .. river_path

-- run scripts
require("scripts.deco")
require("scripts.keys")
require("scripts.autostart")
require("scripts.input")

local rivertile_opts = {
    "-view-padding", "0",
    "-outer-padding", "0",
    "-main-ratio", "0.5",
}

-- replace init with rivertile
-- the lua-posix package is needed to have access to execp
require("posix.unistd").execp("rivertile", rivertile_opts)
