#!/bin/lua

require("river.config.deco")
require("river.config.autostart")
require("river.config.input")
require("river.config.keys")

local rivertile_opts = {
    "-view-padding", "0",
    "-outer-padding", "0",
    "-main-ratio", "0.5",
}

-- replace init with rivertile
-- the lua-posix package is needed to have access to execp
require("posix.unistd").execp("rivertile", rivertile_opts)
