#!/bin/lua

-- required to load scripts
local river_config = os.getenv("HOME") .. "/.config/river/"
package.path = river_config .. "?.lua" .. ";" .. package.path

-- run scripts
require("config.deco")
require("config.keys")
require("config.autostart")
require("config.input")

local rivertile_opts = {
    "-view-padding", "0",
    "-outer-padding", "0",
    "-main-ratio", "0.5",
}

-- replace init with rivertile
-- the lua-posix package is needed to have access to execp
require("posix.unistd").execp("rivertile", rivertile_opts)
