#!/bin/sh

# Pick a color from the screen using hyprpicker

set -e

COLOR_FILE="/tmp/picked_color.png"

color=$(hyprpicker)

# run only if a color was picked
if [ $color ]
then
    # clipboard
    wl-copy $color

    # ImageMagick. The command used to be 'convert', but it is now deprecated
    magick \
        -size 16x16 \
        xc:$color \
        $COLOR_FILE

    notify-send \
        --expire-time=60000 \
        --icon=$COLOR_FILE \
        --app-name="Color" \
        $color
fi
