#!/bin/lua

os.execute("killall corectrl")

require("river.config.theme").setup({ restart = true })
require("river.config.input").setup()
require("river.config.autostart").start({ restart = true })
require("river.config.keys").setup()
